{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = ' AIRPORT_SURROGATE_ID_HASH',
    )
}}

SELECT
{{ dbt_utils.generate_surrogate_key([
    'STR_IDENT','A.LNG_PROVINCE_ID_NMBR'		
]) }} as AIRPORT_SURROGATE_ID_HASH,
LNG_AIRPORT_ID_NMBR,
STR_APPROACH,
STR_CONTACT,
STR_FAX,
STR_WEB_EXPOSURE,
LNG_LATDEG,
MNY_HRS,
STR_LIGHTS,
LNG_DST_PATTERN_HEADER_ID_NMBR,
STR_CUSTOMS,
LNG_UTC,
STR_QUADRANT1,
MNY_LANDFEE,
LNG_WINADJ,
LNG_TIMESTAMP,
STR_AVGAS,
STR_MILITARY,
LNG_LATMIN,
LNG_SUMADJ,
STR_NORTHERN,
LNG_LONMIN,
STR_QUADRANT2,
STR_ILS,
STR_NOTES,
STR_PHONE,
A.DTM_LAST_MOD_DATE,
STR_SUPPTRAINREQ,
A.LNG_CREATION_USER_ID_NMBR,
STR_CAPTAPPREQD,
STR_SUPPTRAINEVENTID,
STR_CUSTOMSPHONE,
STR_JETB,
A.DTM_CREATION_DATE,
LNG_CLOSEST_AIRPORT,
STR_INTENSITY,
LNG_RUNWAY,
STR_ACTIVE_FLAG,
STR_NAME,
LNG_LATSEC,
STR_CUSTOMPROC,
LNG_LONSEC,
STR_JETA,
STR_SECURE_FLAG,
A.LNG_LAST_MOD_USER_ID_NMBR,
STR_IDENT,
LNG_LONDEG,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
    'STR_IDENT','A.LNG_PROVINCE_ID_NMBR'		
]) }} AS ORIGINAL_SURROGATE_ID_HASH,		
P.PROVINCE_SURROGATE_ID_HASH,		
A.LNG_PROVINCE_ID_NMBR
from {{ source('PSS_AMELIARES_DBO', 'TBL_AIRPORT') }} A
left join {{ ref('province_dim') }} P on P.LNG_PROVINCE_ID_NMBR = A.LNG_PROVINCE_ID_NMBR
