{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'CHARGE_CATEGORY_SURROGATE_ID_HASH',
    )
}}

select 
 {{ dbt_utils.generate_surrogate_key([
      'STR_CHARGE_CATEGORY_IDENT '
]) }} as "CHARGE_CATEGORY_SURROGATE_ID_HASH",
STR_CHARGE_CATEGORY_IDENT as "STR_CHARGE_CATEGORY_IDENT",
DTM_LAST_MOD_DATE as "DTM_LASuT_MOD_DATE",
DTM_CREATION_DATE as "DTM_CREATION_DATE",
LNG_LAST_MOD_USER_ID_NMBR as "LNG_LAST_MOD_USER_ID_NMBR",
STR_CHARGE_CATEGORY_NAME as "STR_CHARGE_CATEGORY_NAME",
STR_CHARGE_CATEGORY_ACTIVE_FLAG as "STR_CHARGE_CATEGORY_ACTIVE_FLAG",
TSP_TIMESTAMP as "TSP_TIMESTAMP",
LNG_CREATION_USER_ID_NMBR as "LNG_CREATION_USER_ID_NMBR",
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
LNG_CHARGE_CATEGORY_ID_NMBR as ORIGINAL_SURROGATE_ID_HASH,
TRUE as "LATEST_INDICATOR",
CURRENT_TIMESTAMP() as "INSERTED_TS"
FROM {{ source('PSS_AMELIARES_DBO' ,'TBL_CHARGE_CATEGORY') }}