{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'CHARGE_TYPE_SURROGATE_ID_HASH',
    )
}}

select
{{ dbt_utils.generate_surrogate_key([
      'STR_GL_CHARGE_TYPE_IDENT'
 ]) }} as CHARGE_TYPE_SURROGATE_ID_HASH,
LNG_GL_CHARGE_TYPE_ID_NMBR,
STR_GL_CHARGE_TYPE_DESC,
LNG_GL_CHARGE_PAYMENT_ASSIGNMENT_ORDER_NMBR,
LNG_DEFAULT_RFISC_ID,
chrg_type.LNG_CREATION_USER_ID_NMBR,
chrg_type.DTM_LAST_MOD_DATE,
STR_SALE_ACC_CODE,
STR_CONSUMED_AT_ISSUANCE,
STR_USAGE_ACC_CODE,
STR_REFUNDABLE,
STR_DOC_TYPE_FLAG,
chrg_type.DTM_CREATION_DATE as TSP_TIMESTAMP,
chrg_type.LNG_LAST_MOD_USER_ID_NMBR,
STR_GL_CHARGE_TYPE_IDENT,
chrg_type.DTM_CREATION_DATE,
LNG_RFIC_ID,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
      'STR_GL_CHARGE_TYPE_IDENT'
 ]) }} as ORIGINAL_SURROGATE_ID_HASH,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() as INSERTED_TS,
cc.CHARGE_CATEGORY_SURROGATE_ID_HASH,
chrg_type.LNG_CHARGE_CATEGORY_ID_NMBR
from 
{{ source('PSS_AMELIARES_DBO' ,'TBL_GL_CHARGE_TYPE_DEFINITION') }} chrg_type
left join {{ ref('charge_category_dim') }} cc on chrg_type.LNG_CHARGE_CATEGORY_ID_NMBR=cc.LNG_CHARGE_CATEGORY_ID_NMBR