{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'FLIGHT_LEG_SURROGATE_ID_HASH'
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
     'LF.LNG_RES_LEGS_ID_NMBR','LF.LNG_SKED_DETAIL_ID_NMBR'	
]) }} as FLIGHT_LEG_SURROGATE_ID_HASH,	
LNG_LEG_FLIGHTS_ID_NMBR,		
LF.LNG_SKED_HEADER_ID_NMBR,
LF.DTM_CREATION_DATE,
LNG_RES_STANDBY_SEGMENTS_ID_NMBR,
LF.LNG_CREATION_USER_ID_NMBR,
LF.LNG_RES_SEGMENTS_ID_NMBR,
LF.DTM_CREATION_DATE as TSP_TIMESTAMP,
LF.LNG_RES_LEGS_ID_NMBR,
LNG_LEG_ROUTE_ID_NMBR,
LF.LNG_SKED_DETAIL_ID_NMBR,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
     'LF.LNG_RES_LEGS_ID_NMBR','LF.LNG_SKED_DETAIL_ID_NMBR'	
]) }} as ORIGINAL_SURROGATE_ID_HASH,
SH.SCHEDULE_HEADER_SURROGATE_ID_HASH,					
SD.SCHEDULE_DETAIL_SURROGATE_ID_HASH,					
RL.RESERVATION_LEG_SURROGATE_ID_HASH,					
RS.RESERVATION_SEGMENT_SURROGATE_ID_HASH
FROM {{ source('PSS_AMELIARES_DBO', 'TBL_LEG_FLIGHTS') }}	LF				
LEFT JOIN {{ ref('schedule_header_dim') }} SH ON SH.LNG_SKED_HEADER_ID_NMBR = LF.LNG_SKED_HEADER_ID_NMBR
LEFT JOIN {{ ref('schedule_detail_dim') }} SD ON SD.LNG_SKED_DETAIL_ID_NMBR = LF.LNG_SKED_DETAIL_ID_NMBR
LEFT JOIN {{ ref('reservation_leg_dim') }} RL ON RL.LNG_RES_LEGS_ID_NMBR = LF.LNG_RES_LEGS_ID_NMBR
LEFT JOIN {{ ref('reservation_segment_dim') }} RS ON RS.LNG_RES_SEGMENTS_ID_NMBR = LF.LNG_RES_SEGMENTS_ID_NMBR
