{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'PROVINCE_SURROGATE_ID_HASH',
    )
}}

select 
{{ dbt_utils.generate_surrogate_key([
      'P.LNG_COUNTRY_ID_NMBR','STR_PROVINCE_NAME'
 ]) }} as PROVINCE_SURROGATE_ID_HASH,
LNG_PROVINCE_ID_NMBR,
STR_PROVINCE_NAME,
STR_PROVINCE_ABBREVIATION,
P.STR_DELETED_FLAG,
P.DTM_CREATION_DATE,
P.LNG_CREATION_USER_ID_NMBR,
P.DTM_LAST_MOD_DATE,
P.LNG_LAST_MOD_USER_ID_NMBR,
P.DTM_CREATION_DATE as TSP_TIMESTAMP,
LNG_TAX_CONFIGURATION_ID_NMBR,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
      'P.LNG_COUNTRY_ID_NMBR','STR_PROVINCE_NAME'
 ]) }} as ORIGINAL_SURROGATE_ID_HASH,
CD.COUNTRY_SURROGATE_ID_HASH,
P.LNG_COUNTRY_ID_NMBR
FROM {{ source('PSS_AMELIARES_DBO', 'TBL_PROVINCE_DEFINITION') }} P
LEFT JOIN {{ ref('country_dim') }} cd on cd.LNG_COUNTRY_ID_NMBR = P.LNG_COUNTRY_ID_NMBR
