{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'RESERVATION_SURROGATE_ID_HASH'
    )
}}

select 
 {{ dbt_utils.generate_surrogate_key([
      'LNG_RESERVATION_NMBR'	
 ]) }} as RESERVATION_SURROGATE_ID_HASH,
LNG_RESERVATION_NMBR,
LNG_AGENCY_ID_NMBR,
LNG_TOUROPERATOR_ID_NMBR,
LNG_REASON_ID_NMBR,
STR_REF1,
STR_REF2,
LNG_CONF_NMBR,
STR_LOC_NMBR,
STR_CAX_BY,
DTM_CAX_DATE,
LNG_CAX_USER_ID_NMBR,
LNG_CAX_NUM,
STR_CAX_REASON,
STR_CONTACT_TEL,
STR_CONTACT_EXT,
STR_CONTACT_EMAIL,
STR_CONTACT_NAME,
STR_SPEC_NEEDS,
LNG_SEATS,
STR_HOLD_STATUS,
DTM_HOLD_DATE,
LNG_CURRENCY_ID_NMBR,
MNY_EXCHANGE_RATE,
DTM_CREATION_DATE as TSP_TIMESTAMP,
DTM_CREATION_DATE,
LNG_CREATION_USER_ID_NMBR,
DTM_LAST_MOD_DATE,
LNG_LAST_MOD_USER_ID_NMBR,
DTM_EXPIRE_CREDIT_DATE,
STR_GROUP_BOOKING_FLAG,
STR_ETICKET_FLAG,
BLN_HOLD_OVERWRITTEN,
LNG_DISTRIBUTION_CHANNEL_ID_NMBR,
LNG_PREF_LANGUAGE_ID_NMBR,
STR_GDS_GROUP_NAME,
LNG_DOCUMENT_PROVIDER_ID,
TRUE as "LATEST_INDICATOR",
CURRENT_TIMESTAMP() as "INSERTED_TS",
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
 {{ dbt_utils.generate_surrogate_key([
      'LNG_RESERVATION_NMBR'		
 ]) }} AS ORIGINAL_SURROGATE_ID_HASH		
FROM {{ source('PSS_AMELIARES_DBO', 'TBL_RES_HEADER') }}