{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'RESERVATION_LEG_SURROGATE_ID_HASH'
    )
}}


select 
 {{ dbt_utils.generate_surrogate_key([
      'LNG_LEG_NMBR','RES_LEGS.LNG_RESERVATION_NMBR','LNG_RES_PAX_GROUP_ID_NMBR'	
 ]) }} as RESERVATION_LEG_SURROGATE_ID_HASH,
LNG_RES_LEGS_ID_NMBR,
RES_LEGS.DTM_CREATION_DATE AS TSP_TIMESTAMP,
RES_LEGS.LNG_RESERVATION_NMBR,
STR_PRIVATE_FLAG,
DTM_DATE,
LNG_DEP_AIRPORT_ID_NMBR,
RES_LEGS.LNG_LAST_MOD_USER_ID_NMBR,
STR_LEG_STATUS,
LNG_PROMO_CODE_SUFFIX_ID_NMBR,
LNG_ARR_AIRPORT_ID_NMBR,
STR_REALIZED_REVENUE,
LNG_LEG_NMBR,
STR_SHUTTLE_BUS_FLAG,
RES_LEGS.DTM_LAST_MOD_DATE,
RES_LEGS.LNG_CREATION_USER_ID_NMBR,
STR_EMAIL_ALERT,
MNY_FARE_COST,
STR_COMMENTS,
RES_LEGS.DTM_CREATION_DATE,
LNG_PROMO_CODE_DEFINITION_ID_NMBR,
LNG_RES_PAX_GROUP_ID_NMBR,
STR_TICKET_NMBR,
TRUE as "LATEST_INDICATOR",
CURRENT_TIMESTAMP() as INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
 {{ dbt_utils.generate_surrogate_key([
      'LNG_LEG_NMBR','RES_LEGS.LNG_RESERVATION_NMBR','LNG_RES_PAX_GROUP_ID_NMBR'		
 ]) }}  as ORIGINAL_SURROGATE_ID_HASH,			
RES.RESERVATION_SURROGATE_ID_HASH	
from {{ source('PSS_AMELIARES_DBO', 'TBL_RES_LEGS') }} as RES_LEGS
left join {{ ref('reservation_dim') }} as RES
ON RES.LNG_RESERVATION_NMBR = RES_LEGS.LNG_RESERVATION_NMBR