{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'RESERVATION_PASSENGER_BRIDGE_SURROGATE_ID_HASH'
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
     'LNG_RES_PAX_GROUP_ID_NMBR'	
]) }} as RESERVATION_PASSENGER_BRIDGE_SURROGATE_ID_HASH,
LNG_RES_PAX_GROUP_ID_NMBR,
RP.DTM_LAST_MOD_DATE,
RP.LNG_PAX_ID_NMBR,
RP.LNG_LAST_MOD_USER_ID_NMBR,
STR_SPECIAL_NEEDS,
RP.DTM_CREATION_DATE,
RP.LNG_CREATION_USER_ID_NMBR,
STR_RPG_TYPE,
STR_PAX_STATUS,
RP.LNG_RESERVATION_NMBR,
STR_ENDORSEMENT,
MNY_PAX_WEIGHT,
STR_PAX_REQUEST_NOTES,
STR_RES_OWNER,
LNG_PAX_TYPE_CODES_ID_NMBR,
LNG_PAX_GROUP_LABEL_ID_NMBR,
LNG_FREE_NAME_CORRECTION_COUNT,
RP.DTM_CREATION_DATE as TSP_TIMESTAMP,
STR_TEL_DESTINATION,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
     'LNG_RES_PAX_GROUP_ID_NMBR'	
]) }} as ORIGINAL_SURROGATE_ID_HASH,
RD.RESERVATION_SURROGATE_ID_HASH,			
PASSENGER_SURROGATE_ID_HASH
from {{ source('PSS_AMELIARES_DBO', 'TBL_RES_PAX_GROUP') }} RP
LEFT JOIN  {{ ref('reservation_dim') }} RD ON RD.LNG_RESERVATION_NMBR = RP.LNG_RESERVATION_NMBR
LEFT JOIN  {{ ref('passenger_dim') }} PD ON PD.LNG_PAX_ID_NMBR = RP.LNG_PAX_ID_NMBR
