{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'SCHEDULE_HEADER_SURROGATE_ID_HASH'
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
     'LNG_SKED_HEADER_ID_NMBR'
]) }} as SCHEDULE_HEADER_SURROGATE_ID_HASH,
LNG_SKED_HEADER_ID_NMBR,
STR_LIFE_CYCLE_FLAG,
SH.DTM_CREATION_DATE AS TSP_TIMESTAMP,
SH.LNG_AIRCRAFT_MODEL_ID_NMBR,
SH.LNG_LAST_MOD_USER_ID_NMBR,
DTM_ROUTE_START_DATE,
SH.LNG_CARRIER_ID_OPERATEDBY,
MNY_ROUTE_TOTAL_ESTIMATE_OFF_ON,
SH.LNG_CREATION_USER_ID_NMBR,
SH.STR_ROUTE_NMBR,
SH.LNG_SKED_MASTER_HEADER_ID_NMBR,
DTM_ROUTE_START_LOCAL_DATE,
SH.STR_OPERATING_FLIGHT_NMBR,
SH.DTM_LAST_MOD_DATE,
SH.STR_AIRLINE_CODES_IDENT,
SH.STR_ETICKETABLE,
STR_ACTIVE_FLAG,
LNG_ROUTE_TOTAL_ESTIMATE_CYCLES,
SH.DTM_CREATION_DATE,
SH.STR_OPERATING_AIRLINE_CODE,
MNY_ROUTE_TOTAL_ESTIMATE_OUT_IN,
STR_ROUTE_STATUS,
LNG_ROUTE_TOTAL_ESTIMATE_FLIGHT_DAYS,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
     'LNG_SKED_HEADER_ID_NMBR'
]) }} as ORIGINAL_SURROGATE_ID_HASH,
MH.SCHEDULE_MASTER_HEADER_SURROGATE_ID_HASH		
from {{ source('PSS_AMELIARES_DBO', 'TBL_SKED_HEADER') }} SH	
LEFT JOIN {{ ref('schedule_master_header_dim') }}	MH on SH.LNG_SKED_MASTER_HEADER_ID_NMBR=MH.LNG_SKED_MASTER_HEADER_ID_NMBR
--where SH.LNG_SKED_MASTER_HEADER_ID_NMBR = 20277

/* and DTM_ROUTE_START_DATE = '2017-01-30 15:00:00.000' and SH.LNG_AIRCRAFT_MODEL_ID_NMBR = 3 and STR_ACTIVE_FLAG = 'D' AND 
SH.STR_ROUTE_NMBR = 1100*/
--where SH.LNG_AIRCRAFT_MODEL_ID_NMBR=3 and SH.STR_ROUTE_NMBR='1100' and DTM_ROUTE_START_DATE ='2016-11-21 15:00:00.000' AND STR_ACTIVE_FLAG = 'D'
