{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'SCHEDULE_DETAIL_SURROGATE_ID_HASH'
    )
}}
select
{{ dbt_utils.generate_surrogate_key([
      'LNG_SKED_DETAIL_ID_NMBR'
]) }} as SCHEDULE_DETAIL_SURROGATE_ID_HASH,
LNG_SKED_DETAIL_ID_NMBR,
SD.LNG_SKED_MASTER_DETAIL_ID_NMBR,
MNY_ESTIMATE_OFF_ON_HOURS,
STR_SKED_DETAIL_TYPE,
LNG_FLIGHT_SCHED_LEG_ID_NMBR,
SD.DTM_CREATION_DATE AS TSP_TIMESTAMP,
STR_ALLOWTHRU,
MNY_DISTANCE,
STR_GATE_NMBR,
SD.DTM_LOCAL_ETA_DATE,
DTM_ESTIMATE_OFF,
SD.LNG_AIRCRAFT_ID_NMBR,
SD.LNG_CAPACITY,
DTM_ESTIMATE_OUT,
DTM_ESTIMATE_ON,
SD.LNG_DEP_AIRPORT_ID_NMBR,
SD.STR_AIRLINE_CODES_IDENT,
SD.STR_FLIGHT_NMBR,
SD.LNG_LAST_MOD_USER_ID_NMBR,
SD.LNG_CREATION_USER_ID_NMBR,
DTM_FLIGHT_DATE,
SD.DTM_ETA,
SD.DTM_LAST_MOD_DATE,
SD.LNG_CURTAIL,
SD.DTM_ETD,
SD.LNG_SKED_HEADER_ID_NMBR,
STR_SKED_DETAIL_STATUS,
SD.DTM_LOCAL_ETD_DATE,
SD.LNG_ARR_AIRPORT_ID_NMBR,
SD.DTM_CREATION_DATE,
MNY_ESTIMATE_OUT_IN_HOURS,		
DTM_ESTIMATE_IN,		
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
      'LNG_SKED_DETAIL_ID_NMBR'
]) }} as ORIGINAL_SURROGATE_ID_HASH,
SMD.SCHEDULE_MASTER_DETAIL_SURROGATE_ID_HASH,			
SHD.SCHEDULE_HEADER_SURROGATE_ID_HASH
from {{ source('PSS_AMELIARES_DBO', 'TBL_SKED_DETAIL') }}	SD			
LEFT JOIN {{ ref('schedule_master_detail_dim') }} SMD ON SD.LNG_SKED_MASTER_DETAIL_ID_NMBR=SMD.LNG_SKED_MASTER_DETAIL_ID_NMBR
LEFT JOIN {{ ref('schedule_header_dim') }} SHD ON SD.LNG_SKED_HEADER_ID_NMBR=SHD.LNG_SKED_HEADER_ID_NMBR
--WHERE SD.LNG_SKED_MASTER_DETAIL_ID_NMBR =20277
--WHERE SD.LNG_SKED_HEADER_ID_NMBR = 995 AND DTM_FLIGHT_DATE ='2016-05-30 17:15:00.000'
