{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'SCHEDULE_MASTER_HEADER_SURROGATE_ID_HASH'
    )
}}
select
{{ dbt_utils.generate_surrogate_key([
     'LNG_SKED_MASTER_HEADER_ID_NMBR'
]) }} as SCHEDULE_MASTER_HEADER_SURROGATE_ID_HASH,
LNG_SKED_MASTER_HEADER_ID_NMBR,
STR_ACTIVE,
LNG_CARRIER_ID_OPERATEDBY,
DTM_CREATION_DATE AS TSP_TIMESTAMP,
DTM_FLIGHT_SKED_MASTER_TO_DATE,
LNG_LAST_MOD_USER_ID_NMBR,
LNG_AIRCRAFT_MODEL_ID_NMBR,
DTM_LAST_MOD_DATE,
STR_OPERATING_AIRLINE_CODE,
DTM_CREATION_DATE,
STR_AIRLINE_CODES_IDENT,
STR_ROUTE_NMBR,
LNG_CREATION_USER_ID_NMBR,
STR_OPERATING_FLIGHT_NMBR,
DTM_FLIGHT_SKED_MASTER_FROM_DATE,
STR_ETICKETABLE,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
     'LNG_SKED_MASTER_HEADER_ID_NMBR'
]) }} as ORIGINAL_SURROGATE_ID_HASH
from {{ source('PSS_AMELIARES_DBO', 'TBL_SKED_MASTER_HEADER') }}

--WHERE STR_ROUTE_NMBR = '2802'  AND DTM_FLIGHT_SKED_MASTER_FROM_DATE = '2024-03-06 00:00:00.000' 
--AND DTM_FLIGHT_SKED_MASTER_TO_DATE='2024-03-09 00:00:00.000'AND STR_ACTIVE='Y'

--WHERE STR_ROUTE_NMBR = '655'  AND DTM_FLIGHT_SKED_MASTER_FROM_DATE = '2023-06-21 00:00:00.000' 
--AND DTM_FLIGHT_SKED_MASTER_TO_DATE='2023-06-23 00:00:00.000'AND STR_ACTIVE='Y'

--WHERE STR_ROUTE_NMBR = '506'  AND DTM_FLIGHT_SKED_MASTER_FROM_DATE = '2023-06-30 00:00:00.000' 
--AND DTM_FLIGHT_SKED_MASTER_TO_DATE='2023-06-30 00:00:00.000'AND STR_ACTIVE='Y'

--WHERE STR_ROUTE_NMBR = '1100'  AND LNG_SKED_MASTER_HEADER_ID_NMBR = 1421

