{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'SCHEDULE_MASTER_DETAIL_SURROGATE_ID_HASH',
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
    'LNG_SKED_MASTER_DETAIL_ID_NMBR'
 ]) }} as SCHEDULE_MASTER_DETAIL_SURROGATE_ID_HASH,
MD.LNG_SKED_MASTER_DETAIL_ID_NMBR,
MD.DTM_CREATION_DATE,
DTM_ETA,
LNG_CAPACITY,
LNG_CURTAIL,
STR_SKED_MASTER_DETAIL_TYPE,
MD.STR_AIRLINE_CODES_IDENT,
MD.DTM_LAST_MOD_DATE,
MD.DTM_LOCAL_ETD_DATE,
LNG_DEP_AIRPORT_ID_NMBR,
DTM_LOCAL_ETA_DATE,
MD.LNG_SKED_MASTER_HEADER_ID_NMBR,
MNY_DIST,
MD.LNG_LAST_MOD_USER_ID_NMBR,
DTM_ETD,
MD.DTM_CREATION_DATE AS TSP_TIMESTAMP,
LNG_SEGMENT,
LNG_AIRCRAFT_ID_NMBR,
MD.LNG_CREATION_USER_ID_NMBR,
STR_FLIGHT_NMBR,
LNG_ARR_AIRPORT_ID_NMBR,
STR_SKED_MASTER_DETAIL_STATUS,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
    'LNG_SKED_MASTER_DETAIL_ID_NMBR'
 ]) }} as ORIGINAL_SURROGATE_ID_HASH,
MH.SCHEDULE_MASTER_HEADER_SURROGATE_ID_HASH	
from {{ source('PSS_AMELIARES_DBO', 'TBL_SKED_MASTER_DETAIL') }} MD				
LEFT JOIN {{ ref('schedule_master_header_dim') }} MH on MD.LNG_SKED_MASTER_HEADER_ID_NMBR=MH.LNG_SKED_MASTER_HEADER_ID_NMBR
--WHERE MD.LNG_SKED_MASTER_DETAIL_ID_NMBR = 1209
--where MD.LNG_SKED_MASTER_HEADER_ID_NMBR =1488 and LNG_DEP_AIRPORT_ID_NMBR=4 and MNY_DIST = 0.0000 and LNG_SEGMENT=2 and 
--LNG_ARR_AIRPORT_ID_NMBR =5 and STR_SKED_MASTER_DETAIL_STATUS = 'Y'
