{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'CHARGES_FACT_SURROGATE_ID_HASH'
    )
}}

select  
{{ dbt_utils.generate_surrogate_key([
    'LNG_GL_CHARGES_ID_NMBR',		
]) }} as CHARGES_FACT_SURROGATE_ID_HASH,
chr.DTM_CREATION_DATE as TSP_TIMESTAMP,
MNY_GL_CHARGES_AMOUNT AS CHARGE_AMOUNT,
chr.MNY_EXCHANGE_RATE,
MNY_GL_CURRENCY_CHARGES_TOTAL,
STR_VISIBLE_FLAG,
MNY_GL_CHARGES_TOTAL,
chr.LNG_CREATION_USER_ID_NMBR,
STR_GL_CHARGES_DESC,
LNG_GL_SURCHARGE_ID_NMBR,
STR_CODE,
LNG_GL_DISCOUNTS_ID_NMBR,
STR_SUB_CODE,
DTM_GL_CHARGES_DATE AS BUSINESS_DATE,
LNG_TAX_CONFIGURATION_ID_NMBR,
chr.STR_PRIVATE_FLAG,
MNY_GL_CURRENCY_CHARGES_AMOUNT,
chr.LNG_RES_LEGS_ID_NMBR,
BIT_FULLY_PAID,
MNY_GL_CURRENCY_CHARGES_DISCOUNT,
chr.DTM_LAST_MOD_DATE,
MNY_GL_CHARGES_TAXES,
MNY_GL_CURRENCY_CHARGES_TAXES,
chr.DTM_CREATION_DATE,
STR_REFUNDABLE_CHARGE,
MNY_GL_CURRENCY_CHARGES_DISCOUNT AS DISCOUNT_AMOUNT,
chr.STR_DOC_TYPE_FLAG,
chr.LNG_RESERVATION_NMBR,
STR_GL_CHARGES_NOTES,
chr.LNG_LAST_MOD_USER_ID_NMBR,
TRUE AS LOGICALLY_DELETED_INDICATOR,			
CURRENT_TIMESTAMP() AS INSERTED_TS,	
cd.CHARGE_TYPE_SURROGATE_ID_HASH,			
cur_dim.CURRENCY_SURROGATE_ID_HASH,
chr.LNG_GL_CHARGE_TYPE_ID_NMBR,
chr.LNG_CURRENCY_ID_NMBR,			
res.RESERVATION_SURROGATE_ID_HASH,				
res_leg.RESERVATION_LEG_SURROGATE_ID_HASH,
MNY_GL_CHARGES_AMOUNT,
DTM_GL_CHARGES_DATE,
MNY_GL_CHARGES_DISCOUNT
from {{ source('PSS_AMELIARES_DBO', 'TBL_GL_CHARGES') }} chr

LEFT JOIN {{ ref('charge_type_dim') }} cd on cd.LNG_GL_CHARGE_TYPE_ID_NMBR = chr.LNG_GL_CHARGE_TYPE_ID_NMBR

left join {{ ref('currency_dim') }} cur_dim on cur_dim.LNG_CURRENCY_ID_NMBR = chr.LNG_CURRENCY_ID_NMBR

left join {{ ref('reservation_dim') }} res on chr.LNG_RESERVATION_NMBR = res.LNG_RESERVATION_NMBR

LEFT JOIN  {{ ref('reservation_leg_dim') }} res_leg on res_leg.LNG_RES_LEGS_ID_NMBR = chr.LNG_RES_LEGS_ID_NMBR
