{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        unique_key = 'RESERVATION_STATUS_FACT_SURROGATE_ID_HASH'
    )
}}

SELECT 
{{ dbt_utils.generate_surrogate_key([
     'RSL.LNG_RES_PAX_GROUP_ID_NMBR'	
]) }} as RESERVATION_STATUS_FACT_SURROGATE_ID_HASH,
RSL.DTM_CREATION_DATE,
RSL.LNG_LAST_MOD_USER_ID_NMBR,
RSL.LNG_RESERVATION_NMBR,
RSL.STR_RES_SEGMENTS,
RSL.LNG_CREATION_USER_ID_NMBR,
RSL.DTM_LAST_MOD_DATE,
RSL.DTM_CREATION_DATE AS TSP_TIMESTAMP,
TRUE as LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
RPB.RESERVATION_PASSENGER_BRIDGE_SURROGATE_ID_HASH
FROM {{ source('PSS_AMELIARES_DBO', 'TBL_RES_SEGMENTS_LEVEL') }} RSL
LEFT JOIN {{ ref('reservation_passenger_bridge') }} RPB ON RPB.LNG_RES_PAX_GROUP_ID_NMBR = RSL.LNG_RES_PAX_GROUP_ID_NMBR
