{{
    config(
        materialized = 'view',
    )
}}

select
CASE
    WHEN t4.STR_AGENCY_NAME <> '' AND t5.STR_USER_LOGON_NAME <> '' then 'Amelia'
    else 'MISChoice'
end as "SOURCE",
t1.LNG_RESERVATION_NMBR as "RES_NMBR",
to_varchar(t1.DTM_GL_PAYMENTS_DATE,'MM/DD/YYYY HH12:MI:SS AM') as PAYMENT_DATE,
t2.STR_GL_PAYMENT_METHOD_DESC as PAYMENT_TYPE,
round(t1.MNY_GL_PAYMENTS_AMOUNT,2) AS PAYMENT_AMT,
t3.STR_REF1 as PNR,
t4.STR_AGENCY_NAME as SALES_AGENCY,
t5.STR_USER_NAME as "PAYMENT USERNAME"

FROM {{ source('PSS_AMELIARES_DBO' ,'TBL_GL_PAYMENTS') }} t1
left join {{ source('PSS_AMELIARES_DBO' ,'TBL_GL_PAYMENT_METHOD') }} t2 on t2.LNG_GL_PAYMENT_METHOD_ID_NMBR = t1.LNG_GL_PAYMENT_METHOD_ID_NMBR
LEFT JOIN {{ source('PSS_AMELIARES_DBO', 'TBL_RES_HEADER') }} t3 on t3.LNG_RESERVATION_NMBR = t1.LNG_RESERVATION_NMBR
LEFT join {{ source('PSS_AMELIARES_DBO', 'TBL_AGENCY') }} t4 on t4.LNG_AGENCY_ID_NMBR = t3.LNG_AGENCY_ID_NMBR
LEFT join {{ source('PSS_AMELIARES_DBO', 'TBL_USERS') }} t5 ON t1.LNG_CREATION_USER_ID_NMBR  = t5.lng_User_Id_Nmbr