{{
    config(
        materialized = 'view',
        incremental_strategy = 'merge',
        unique_key = 'RESERVATION_HEADER_SURROGATE_ID_HASH'
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
      'LNG_RESERVATION_NMBR'
 ]) }} as RESERVATION_HEADER_SURROGATE_ID_HASH,
LNG_RESERVATION_NMBR,
LNG_LAST_MOD_USER_ID_NMBR,
STR_CONTACT_EXT,
LNG_CONF_NMBR,
LNG_AGENCY_ID_NMBR,
STR_GDS_GROUP_NAME,
STR_CAX_REASON,
LNG_CAX_NUM,
LNG_SEATS,
LNG_CURRENCY_ID_NMBR,
STR_ETICKET_FLAG,
STR_REF1,
STR_CONTACT_NAME,
STR_CONTACT_EMAIL,
LNG_REASON_ID_NMBR,
STR_REF2,
STR_CAX_BY,
DTM_CREATION_DATE,
DTM_CREATION_DATE as TSP_TIMESTAMP,
BLN_HOLD_OVERWRITTEN,
DTM_LAST_MOD_DATE,
STR_SPEC_NEEDS,
LNG_DOCUMENT_PROVIDER_ID,
DTM_HOLD_DATE,
DTM_EXPIRE_CREDIT_DATE,
STR_HOLD_STATUS,
LNG_TOUROPERATOR_ID_NMBR,
LNG_CAX_USER_ID_NMBR,
LNG_PREF_LANGUAGE_ID_NMBR,
LNG_DISTRIBUTION_CHANNEL_ID_NMBR,
STR_GROUP_BOOKING_FLAG,
STR_CONTACT_TEL,
MNY_EXCHANGE_RATE,
STR_LOC_NMBR,
DTM_CAX_DATE,
LNG_CREATION_USER_ID_NMBR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
      'LNG_RESERVATION_NMBR'
 ]) }} as ORIGINAL_SURROGATE_ID_HASH

FROM {{ source('PSS_AMELIARES_DBO' ,'TBL_RES_HEADER') }}
