{{
    config(
        materialized = 'view',
        incremental_strategy = 'merge',
        unique_key = 'GL_PAYMENTS_SURROGATE_ID_HASH'
    )
}}
select 
{{ dbt_utils.generate_surrogate_key([
      'LNG_GL_PAYMENTS_ID_NMBR'
 ]) }} as GL_PAYMENTS_SURROGATE_ID_HASH,

LNG_GL_PAYMENTS_ID_NMBR,
DTM_CREATION_DATE,
LNG_GL_PAYMENTS_RECEIPT_NMBR,
STR_GL_PAYMENTS_DESC,
DTM_LAST_MOD_DATE,
STR_GL_PAYMENTS_PAYER,
MNY_EXCHANGE_RATE,
BIT_FULLY_USED,
LNG_RESERVATION_NMBR,
LNG_LAST_MOD_USER_ID_NMBR,
LNG_GL_PAYMENT_METHOD_ID_NMBR,
LNG_CURRENCY_ID_NMBR,
STR_GL_PAYMENTS_NOTES,
MNY_GL_CURRENCY_PAYMENTS_AMOUNT,
LNG_CREATION_USER_ID_NMBR,
DTM_GL_PAYMENTS_DATE,
DTM_CREATION_DATE AS TSP_TIMESTAMP,
MNY_GL_PAYMENTS_AMOUNT,
LNG_RES_PAX_GROUP_ID_NMBR,
LNG_USER_AIRPORT_ID_NMBR,
TRUE AS LATEST_INDICATOR,
CURRENT_TIMESTAMP() AS INSERTED_TS,
to_timestamp('1900-01-01','YYYY-MM-DD') as EFFECTIVE_DATETIME,
NULL AS EXPIRY_DATETIME,
{{ dbt_utils.generate_surrogate_key([
      'LNG_GL_PAYMENTS_ID_NMBR'
 ]) }} as ORIGINAL_SURROGATE_ID_HASH

FROM {{ source('PSS_AMELIARES_DBO' ,'TBL_GL_PAYMENTS') }}

