{% macro MIS_STAGE_LOAD() %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PAX();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PAX_ANCILLARY_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_SEGMENTS_TO_BAGS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PASSENGER_ANCILLARY_CHARGE_TAXES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PAX_ANCILLARY_PAYMENTS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_AIRPORTS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_BAG_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_CHARGE_CATEGORIES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_MISCELLANEOUS_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_SEAT_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_TICKET_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_SEGMENTS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PAX_ANCILLARY_TRANSACTIONS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_TEMPLATES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_BAG_TYPES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_CURRENCIES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_PASSENGER_ANCILLARY_TAXES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_SSR_CATEGORIES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_SSR_CODES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_TAXES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_USERS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_TEMPLATES_TO_CHARGES();") %}    
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_BAGS();") %} 
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_AIRCRAFT_SEAT_CHARGES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_AIRCRAFT_SEAT_TEMPLATES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_ANCILLARY_WAIVE_CATEGORIES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_BAG_TRACKING();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_BLACKLIST_PAX();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_BLOCKED_SEATS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_CLOSEOUT_TRANSACTIONS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_EXCEPTION_REPORTS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_REMARKS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_SEGMENT_ANNOUNCEMENTS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_FLIGHT_SEGMENT_DELAYS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_TRAVEL_DOCUMENT_SECURITY_RESPONSES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_USER_CATEGORIES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_VETTING_SECURITY_RESPONSES();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_WORKFLOWS();") %}
  {% do run_query("call STAGE_PROD.MIS_DBO.PROC_STG_WORKFLOWSTEPS();") %}
{% endmacro %}