version: 2

sources:
  - name: INFLIGHTSALES_LIFEBOB
    database: FIVETRAN_DATABASE_CLEAN
    schema: INFLIGHTSALES_LIFEBOB
    tables:
      - name: FLIGHTS
        description: This is a cleansed data

  - name: INFLIGHTSALES_LIFEBOB1
    database: FIVETRAN_DATABASE
    schema: INFLIGHTSALES_LIFEBOB
    tables:
      - name: FLIGHTS
        description: This is a raw data
  - name: PSS_AMELIARES_DBO
    database: FIVETRAN_DATABASE
    schema: PSS_AMELIARES_DBO
    tables:
      - name: TBL_CURRENCY
      - name: TBL_GL_CHARGE_TYPE_DEFINITION
      - name: TBL_CHARGE_CATEGORY
      - name: TBL_GL_CHARGES
      - name: TBL_RES_HEADER
      - name: TBL_RES_LEGS


          

                  
                
                  

          
                  