version: 2

sources:
  - name: INFLIGHTSALES_LIFEBOB
    database: FIVETRAN_DATABASE_CLEAN
    schema: INFLIGHTSALES_LIFEBOB
    tables:
      - name: FLIGHTS
        description: This is a cleansed data

  - name: INFLIGHTSALES_LIFEBOB1
    database: FIVETRAN_DATABASE
    schema: INFLIGHTSALES_LIFEBOB
    tables:
      - name: FLIGHTS
        description: This is a raw data
  - name: PSS_AMELIARES_DBO
    database: FIVETRAN_DATABASE
    schema: PSS_AMELIARES_DBO
    tables:
      - name: TBL_CURRENCY
      - name: TBL_GL_CHARGE_TYPE_DEFINITION
      - name: TBL_CHARGE_CATEGORY
      - name: TBL_GL_CHARGES
      - name: TBL_RES_HEADER
      - name: TBL_RES_SEGMENTS
      - name: TBL_RES_LEGS
      - name: TBL_COUNTRY
      - name: TBL_PROVINCE_DEFINITION
      - name: TBL_AIRPORT
      - name: TBL_RES_PAX_GROUP
      - name: TBL_SKED_MASTER_HEADER
      - name: TBL_SKED_HEADER
      - name: TBL_SKED_MASTER_DETAIL
      - name: TBL_SKED_DETAIL
      - name: TBL_PAX
      - name: TBL_RES_SEGMENTS_LEVEL
      - name: TBL_LEG_FLIGHTS
      - name: TBL_GL_PAYMENTS
      - name: TBL_GL_PAYMENT_METHOD
      - name: TBL_AGENCY
      - name: TBL_USERS
      - name: TBL_SKED_FLIGHT_WATCH_JOURNEY_LOG
      - name: TBL_RES_CHECKIN
      - name: TBL_TAX_CONFIGURATION
      - name: TBL_SKEDDETAIL_LEVELOFSERVICE 
      - name: TBL_FARE_CLASS     
      - name: TBL_CHARGES_FARECLASS_XREF 
      
      - name: TBL_LEVEL_OF_SERVICE      
      - name: TBL_SEAT_ALLOCATION 
  
  - name: AMELIA_DBO
    database: STAGE_DEV
    schema: AMELIA_DBO
    tables:
      - name: STG_PAX

      
      


          

                  
                
                  

          
                  